name = "my-cruz-app"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist/client"

[[d1_databases]]
binding = "DB"
database_name = "my-cruz-app-db"
database_id = ""
