import type { CruzConfig } from '../define-config';
import type { CloudflareEnvironment } from './types';

/**
 * Generate a complete wrangler.toml string from CruzConfig + environment resource IDs.
 *
 * This is called at deploy time to produce the wrangler.toml that wrangler uses.
 * Secrets are NOT included — they are set via `wrangler secret put`.
 */
export function generateWranglerToml(
  config: CruzConfig,
  env: CloudflareEnvironment,
  envName: string
): string {
  const lines: string[] = [];
  const bindings = config.bindings ?? {};

  // Header
  lines.push('# Auto-generated by cruz-deploy. Do not edit manually.');
  lines.push(`# Environment: ${envName}`);
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push('');

  // Core settings
  lines.push(`name = "${config.name}"`);

  if (config.compatibilityDate) {
    lines.push(`compatibility_date = "${config.compatibilityDate}"`);
  }

  if (config.compatibilityFlags?.length) {
    const flags = config.compatibilityFlags
      .map((f) => `"${f}"`)
      .join(', ');
    lines.push(`compatibility_flags = [${flags}]`);
  }

  // Pages build output
  lines.push('pages_build_output_dir = "./dist/client"');

  // Note: account_id is NOT supported in Pages wrangler.toml
  // Wrangler resolves account from OAuth login or CLOUDFLARE_ACCOUNT_ID env var

  // D1 Database
  if (bindings.d1 && env.d1) {
    lines.push('');
    lines.push('[[d1_databases]]');
    lines.push('binding = "DB"');
    lines.push(`database_name = "${env.d1.name}"`);
    lines.push(`database_id = "${env.d1.databaseId}"`);
    lines.push(
      `migrations_dir = "${config.migrationsDir ?? './src/database/migrations'}"`
    );
  }

  // KV Namespace
  if (bindings.kv && env.kv) {
    lines.push('');
    lines.push('[[kv_namespaces]]');
    lines.push('binding = "CACHE_KV"');
    lines.push(`id = "${env.kv.namespaceId}"`);
  }

  // R2 Bucket
  if (bindings.r2 && env.r2) {
    lines.push('');
    lines.push('[[r2_buckets]]');
    lines.push('binding = "STORAGE"');
    lines.push(`bucket_name = "${env.r2.name}"`);
  }

  // Workers AI
  if (bindings.ai) {
    lines.push('');
    lines.push('[ai]');
    lines.push('binding = "AI"');
  }

  // Vectorize
  if (bindings.vectorize && env.vectorize?.length) {
    for (const v of env.vectorize) {
      lines.push('');
      lines.push('[[vectorize]]');
      lines.push(`binding = "VECTORIZE"`);
      lines.push(`index_name = "${v.indexName}"`);
    }
  }

  // Queues — built-in JOBS_QUEUE + user-defined queues from config
  if (bindings.queues) {
    // Built-in jobs queue (always present when queues are enabled)
    const jobsQueueName = `${config.name}-jobs`;
    lines.push('');
    lines.push('# Built-in jobs queue');
    lines.push('[[queues.producers]]');
    lines.push('binding = "JOBS_QUEUE"');
    lines.push(`queue = "${jobsQueueName}"`);
    lines.push('');
    lines.push('[[queues.consumers]]');
    lines.push(`queue = "${jobsQueueName}"`);
    lines.push('max_batch_size = 10');
    lines.push('max_batch_timeout = 30');

    // User-defined queues from cruz.config.ts
    if (config.queues?.length) {
      for (const q of config.queues) {
        const binding = q.binding ?? `${q.name.toUpperCase().replace(/-/g, '_')}_QUEUE`;
        lines.push('');
        lines.push(`# Queue: ${q.name}`);
        lines.push('[[queues.producers]]');
        lines.push(`binding = "${binding}"`);
        lines.push(`queue = "${q.name}"`);
        lines.push('');
        lines.push('[[queues.consumers]]');
        lines.push(`queue = "${q.name}"`);
        lines.push(`max_batch_size = ${q.maxBatchSize ?? 10}`);
        lines.push(`max_batch_timeout = ${q.maxBatchTimeout ?? 30}`);
      }
    }

    // Legacy: env-discovered queues (from `cruz init`)
    if (env.queues?.length) {
      for (const q of env.queues) {
        // Skip if already configured via config.queues
        const alreadyConfigured = config.queues?.some(
          (cq) => cq.name === q.name
        );
        if (alreadyConfigured) continue;
        // Skip the built-in jobs queue
        if (q.name === jobsQueueName) continue;

        lines.push('');
        lines.push('[[queues.producers]]');
        lines.push(`binding = "${q.name.toUpperCase().replace(/-/g, '_')}_QUEUE"`);
        lines.push(`queue = "${q.name}"`);
        lines.push('');
        lines.push('[[queues.consumers]]');
        lines.push(`queue = "${q.name}"`);
        lines.push('max_batch_size = 10');
        lines.push('max_batch_timeout = 30');
      }
    }
  }

  // Scheduled triggers (cron)
  if (config.scheduled?.length) {
    lines.push('');
    lines.push('# Scheduled triggers (cron)');
    lines.push('[triggers]');
    const crons = config.scheduled.map((s) => `"${s.cron}"`).join(', ');
    lines.push(`crons = [${crons}]`);
  }

  // Rate Limiting
  if (bindings.rateLimiting) {
    lines.push('');
    lines.push('[[ratelimits]]');
    lines.push('binding = "RATE_LIMITER"');
    lines.push('namespace_id = "1001"');
    lines.push('simple = { limit = 100, period = 60 }');
    lines.push('');
    lines.push('[[ratelimits]]');
    lines.push('binding = "AGENT_RATE_LIMITER"');
    lines.push('namespace_id = "1002"');
    lines.push('simple = { limit = 1000, period = 60 }');
  }

  // Vars
  const vars: Record<string, string> = {};

  // Base vars from config
  if (config.vars) {
    Object.assign(vars, config.vars);
  }

  // Environment-specific vars (override base)
  const envConfig = config.environments?.[envName];
  if (envConfig?.vars) {
    Object.assign(vars, envConfig.vars);
  }

  // Feature flags
  if (config.features?.orgs === false) {
    vars['ORGS_ENABLED'] = 'false';
  }

  // Email provider var
  if (config.email?.provider && config.email.provider !== 'none') {
    vars['EMAIL_PROVIDER'] = config.email.provider;
  }

  // AI Gateway var
  if (bindings.aiGateway) {
    vars['CF_AI_GATEWAY_ID'] = config.name;
  }

  if (Object.keys(vars).length > 0) {
    lines.push('');
    lines.push('[vars]');
    for (const [key, value] of Object.entries(vars).sort(([a], [b]) =>
      a.localeCompare(b)
    )) {
      lines.push(`${key} = "${value}"`);
    }
  }

  lines.push('');
  return lines.join('\n');
}
