#!/bin/bash
set -e

# ============================================
# Loud Chorus - One-Shot Setup Script
# ============================================
# Usage: ./scripts/setup.sh <project-name> <cloudflare-account-id> <cloudflare-api-token>
#
# This script will:
# 1. Generate all secrets and create .env
# 2. Create Cloudflare resources (D1, R2, KV, Queue)
# 3. Update wrangler.toml with resource IDs
# 4. Run database migrations
# 5. Optionally deploy to Cloudflare

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Check arguments
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 <project-name> <cloudflare-account-id> <cloudflare-api-token>"
    echo ""
    echo "Arguments:"
    echo "  project-name           Name for your project (lowercase, no spaces)"
    echo "  cloudflare-account-id  Your Cloudflare Account ID"
    echo "  cloudflare-api-token   API Token with D1/R2/KV/Queue permissions"
    echo ""
    echo "Example:"
    echo "  $0 loudchorus abc123def456 your-api-token"
    exit 1
fi

PROJECT_NAME="$1"
CF_ACCOUNT_ID="$2"
CF_API_TOKEN="$3"

# Validate project name
if [[ ! "$PROJECT_NAME" =~ ^[a-z0-9-]+$ ]]; then
    log_error "Project name must be lowercase alphanumeric with dashes only"
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
WEB_DIR="$ROOT_DIR/apps/demo"

cd "$ROOT_DIR"

echo ""
echo "============================================"
echo "  Loud Chorus Setup"
echo "============================================"
echo ""
log_info "Project: $PROJECT_NAME"
log_info "Account: $CF_ACCOUNT_ID"
echo ""

# Generate secrets
generate_secret() {
    openssl rand -base64 32 | tr -d '\n'
}

# Step 1: Create .env file
log_info "Step 1: Creating .env file..."

if [ -f ".env" ]; then
    log_warn ".env already exists, backing up to .env.backup"
    cp .env .env.backup
fi

SESSION_SECRET=$(generate_secret)
CSRF_SECRET=$(generate_secret)
JWT_SECRET=$(generate_secret)
JWT_REFRESH_SECRET=$(generate_secret)
WORKER_CALLBACK_SECRET=$(generate_secret)

cat > .env << EOF
# ============================================
# Loud Chorus - Generated Configuration
# ============================================
# Generated by setup.sh on $(date)

# Application
NODE_ENV=development
APP_URL=http://localhost:5000
APP_NAME=Loud Chorus

# Cloudflare
CLOUDFLARE_ACCOUNT_ID=$CF_ACCOUNT_ID
CLOUDFLARE_API_TOKEN=$CF_API_TOKEN

# Security Secrets (auto-generated)
SESSION_SECRET=$SESSION_SECRET
CSRF_SECRET=$CSRF_SECRET
JWT_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET

# Song Processor Worker
WORKER_CALLBACK_SECRET=$WORKER_CALLBACK_SECRET
CALLBACK_API_URL=http://localhost:5000/api/jobs/callback

# Queue ID - will be filled in after creation
CLOUDFLARE_QUEUE_ID=

# R2 External Access (for song-processor worker)
# Create at: R2 > Manage R2 API Tokens
R2_ACCESS_KEY_ID=
R2_SECRET_ACCESS_KEY=
R2_BUCKET_NAME=${PROJECT_NAME}-uploads

# Email (configure for production)
EMAIL_FROM=noreply@yourdomain.com
EMAIL_FROM_NAME=Loud Chorus

# OAuth (optional)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# Stripe (optional)
STRIPE_SECRET_KEY=
STRIPE_PUBLISHABLE_KEY=
STRIPE_WEBHOOK_SECRET=
EOF

log_success ".env created with generated secrets"

# Step 2: Export for wrangler
export CLOUDFLARE_ACCOUNT_ID="$CF_ACCOUNT_ID"
export CLOUDFLARE_API_TOKEN="$CF_API_TOKEN"

# Step 3: Create Cloudflare resources
log_info "Step 2: Creating Cloudflare resources..."

cd "$WEB_DIR"

# Create D1 Database
log_info "  Creating D1 database: ${PROJECT_NAME}-db"
D1_OUTPUT=$(npx wrangler d1 create "${PROJECT_NAME}-db" 2>&1 || true)
if echo "$D1_OUTPUT" | grep -q "already exists"; then
    log_warn "  D1 database already exists"
    D1_ID=$(npx wrangler d1 list 2>&1 | grep "${PROJECT_NAME}-db" | awk '{print $1}' || echo "")
else
    D1_ID=$(echo "$D1_OUTPUT" | grep -oE '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}' | head -1)
    log_success "  D1 database created: $D1_ID"
fi

# Create R2 Bucket
log_info "  Creating R2 bucket: ${PROJECT_NAME}-uploads"
R2_OUTPUT=$(npx wrangler r2 bucket create "${PROJECT_NAME}-uploads" 2>&1 || true)
if echo "$R2_OUTPUT" | grep -q "already exists"; then
    log_warn "  R2 bucket already exists"
else
    log_success "  R2 bucket created"
fi

# Create KV Namespace
log_info "  Creating KV namespace: ${PROJECT_NAME}-cache"
KV_OUTPUT=$(npx wrangler kv namespace create "${PROJECT_NAME}-cache" 2>&1 || true)
if echo "$KV_OUTPUT" | grep -q "already exists"; then
    log_warn "  KV namespace already exists"
    KV_ID=$(npx wrangler kv namespace list 2>&1 | grep -A1 "${PROJECT_NAME}-cache" | grep -oE '[a-f0-9]{32}' | head -1 || echo "")
else
    KV_ID=$(echo "$KV_OUTPUT" | grep -oE '[a-f0-9]{32}' | head -1)
    log_success "  KV namespace created: $KV_ID"
fi

# Create Queue
log_info "  Creating Queue: ${PROJECT_NAME}-song-import-queue"
QUEUE_OUTPUT=$(npx wrangler queues create "${PROJECT_NAME}-song-import-queue" 2>&1 || true)
if echo "$QUEUE_OUTPUT" | grep -q "already exists"; then
    log_warn "  Queue already exists"
else
    log_success "  Queue created"
fi

# Get Queue ID
QUEUE_ID=$(npx wrangler queues list 2>&1 | grep "${PROJECT_NAME}-song-import-queue" | awk '{print $1}' || echo "")

cd "$ROOT_DIR"

# Step 4: Update .env with Queue ID
if [ -n "$QUEUE_ID" ]; then
    sed -i "s/CLOUDFLARE_QUEUE_ID=.*/CLOUDFLARE_QUEUE_ID=$QUEUE_ID/" .env
    log_success "Queue ID added to .env: $QUEUE_ID"
fi

# Step 5: Update wrangler.toml
log_info "Step 3: Updating wrangler.toml..."

WRANGLER_FILE="$WEB_DIR/wrangler.toml"

if [ -f "$WRANGLER_FILE" ]; then
    # Update database_id
    if [ -n "$D1_ID" ]; then
        sed -i "s/database_id = \"[^\"]*\"/database_id = \"$D1_ID\"/" "$WRANGLER_FILE"
        log_success "  Updated D1 database_id"
    fi

    # Update KV namespace id
    if [ -n "$KV_ID" ]; then
        sed -i "s/^id = \"[a-f0-9]*\"/id = \"$KV_ID\"/" "$WRANGLER_FILE"
        log_success "  Updated KV namespace id"
    fi

    # Update bucket name
    sed -i "s/bucket_name = \"[^\"]*\"/bucket_name = \"${PROJECT_NAME}-uploads\"/" "$WRANGLER_FILE"
    log_success "  Updated R2 bucket name"

    # Update queue name
    sed -i "s/queue = \"[^\"]*\"/queue = \"${PROJECT_NAME}-song-import-queue\"/" "$WRANGLER_FILE"
    log_success "  Updated Queue name"

    # Update database name
    sed -i "s/database_name = \"[^\"]*\"/database_name = \"${PROJECT_NAME}-db\"/" "$WRANGLER_FILE"
    log_success "  Updated D1 database name"
else
    log_warn "wrangler.toml not found, skipping updates"
fi

# Step 6: Run migrations
log_info "Step 4: Running database migrations..."

cd "$WEB_DIR"
npx wrangler d1 migrations apply "${PROJECT_NAME}-db" --local 2>&1 || log_warn "Local migrations may have already been applied"
log_success "Local database migrations complete"

cd "$ROOT_DIR"

# Step 7: Install dependencies if needed
if [ ! -d "node_modules" ]; then
    log_info "Step 5: Installing dependencies..."
    npm install
    log_success "Dependencies installed"
fi

# Done!
echo ""
echo "============================================"
echo -e "${GREEN}  Setup Complete!${NC}"
echo "============================================"
echo ""
echo "Resources created:"
echo "  - D1 Database: ${PROJECT_NAME}-db"
echo "  - R2 Bucket: ${PROJECT_NAME}-uploads"
echo "  - KV Namespace: ${PROJECT_NAME}-cache"
echo "  - Queue: ${PROJECT_NAME}-song-import-queue"
echo ""
echo "Next steps:"
echo "  1. Start development server:"
echo "     npm run dev"
echo ""
echo "  2. (Optional) Configure external services in .env:"
echo "     - R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY (for song-processor)"
echo "     - GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET (for OAuth)"
echo "     - STRIPE_* keys (for billing)"
echo ""
echo "  3. Deploy to production:"
echo "     npm run build && npm run deploy"
echo ""
echo "  4. Run remote migrations after first deploy:"
echo "     cd apps/demo && npx wrangler d1 migrations apply ${PROJECT_NAME}-db --remote"
echo ""
